### ISSUE TITLE
Create db-schema

### ISSUE THREAD

**Issue by mpatapenka** [trollsrulls/PersonalAccess-Project#1]
Create db-schema for project

**Comment by mpatapenka** [comment]
![image](https://cloud.githubusercontent.com/assets/10284052/13091067/6937cda2-d50a-11e5-8ddd-e25700cb275c.png)

**Comment by mpatapenka** [comment]
1. fix id sizes
2. check descriptions
3. create sql cript

**Comment by trollsrulls** [comment]
With fixed id sizes
![image](https://cloud.githubusercontent.com/assets/10284052/13117661/fd3f66d4-d5b1-11e5-9d56-0f8c64119336.png)

**Comment by mpatapenka** [comment]
Final version
![image](https://cloud.githubusercontent.com/assets/10284052/13407283/b443726e-df38-11e5-9092-6a63d717d9af.png)
